// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Expertise is the predicate function for expertise builders.
type Expertise func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
