// Code generated by entc, DO NOT EDIT.

package department

const (
	// Label holds the string label denoting the department type in the database.
	Label = "department"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDepartmentName holds the string denoting the departmentname field in the database.
	FieldDepartmentName = "department_name"

	// EdgeDepartmentUser holds the string denoting the departmentuser edge name in mutations.
	EdgeDepartmentUser = "DepartmentUser"

	// Table holds the table name of the department in the database.
	Table = "departments"
	// DepartmentUserTable is the table the holds the DepartmentUser relation/edge.
	DepartmentUserTable = "users"
	// DepartmentUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	DepartmentUserInverseTable = "users"
	// DepartmentUserColumn is the table column denoting the DepartmentUser relation/edge.
	DepartmentUserColumn = "DepartmentID"
)

// Columns holds all SQL columns for department fields.
var Columns = []string{
	FieldID,
	FieldDepartmentName,
}
