// Code generated by entc, DO NOT EDIT.

package position

const (
	// Label holds the string label denoting the position type in the database.
	Label = "position"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPositionID holds the string denoting the positionid field in the database.
	FieldPositionID = "position_id"
	// FieldPositionName holds the string denoting the positionname field in the database.
	FieldPositionName = "position_name"

	// EdgePositionUser holds the string denoting the positionuser edge name in mutations.
	EdgePositionUser = "PositionUser"

	// Table holds the table name of the position in the database.
	Table = "positions"
	// PositionUserTable is the table the holds the PositionUser relation/edge.
	PositionUserTable = "users"
	// PositionUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	PositionUserInverseTable = "users"
	// PositionUserColumn is the table column denoting the PositionUser relation/edge.
	PositionUserColumn = "position_position_user"
)

// Columns holds all SQL columns for position fields.
var Columns = []string{
	FieldID,
	FieldPositionID,
	FieldPositionName,
}
