// Code generated by entc, DO NOT EDIT.

package expertise

const (
	// Label holds the string label denoting the expertise type in the database.
	Label = "expertise"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldExpertiseID holds the string denoting the expertiseid field in the database.
	FieldExpertiseID = "expertise_id"
	// FieldExpertiseName holds the string denoting the expertisename field in the database.
	FieldExpertiseName = "expertise_name"
	// FieldLicenes holds the string denoting the licenes field in the database.
	FieldLicenes = "licenes"

	// EdgeExpertiseUser holds the string denoting the expertiseuser edge name in mutations.
	EdgeExpertiseUser = "ExpertiseUser"

	// Table holds the table name of the expertise in the database.
	Table = "expertises"
	// ExpertiseUserTable is the table the holds the ExpertiseUser relation/edge.
	ExpertiseUserTable = "users"
	// ExpertiseUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ExpertiseUserInverseTable = "users"
	// ExpertiseUserColumn is the table column denoting the ExpertiseUser relation/edge.
	ExpertiseUserColumn = "expertise_expertise_user"
)

// Columns holds all SQL columns for expertise fields.
var Columns = []string{
	FieldID,
	FieldExpertiseID,
	FieldExpertiseName,
	FieldLicenes,
}
