// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/beam19857/app/ent/expertise"
	"github.com/beam19857/app/ent/user"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ExpertiseCreate is the builder for creating a Expertise entity.
type ExpertiseCreate struct {
	config
	mutation *ExpertiseMutation
	hooks    []Hook
}

// SetExpertiseName sets the ExpertiseName field.
func (ec *ExpertiseCreate) SetExpertiseName(s string) *ExpertiseCreate {
	ec.mutation.SetExpertiseName(s)
	return ec
}

// AddExpertiseUserIDs adds the ExpertiseUser edge to User by ids.
func (ec *ExpertiseCreate) AddExpertiseUserIDs(ids ...int) *ExpertiseCreate {
	ec.mutation.AddExpertiseUserIDs(ids...)
	return ec
}

// AddExpertiseUser adds the ExpertiseUser edges to User.
func (ec *ExpertiseCreate) AddExpertiseUser(u ...*User) *ExpertiseCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ec.AddExpertiseUserIDs(ids...)
}

// Mutation returns the ExpertiseMutation object of the builder.
func (ec *ExpertiseCreate) Mutation() *ExpertiseMutation {
	return ec.mutation
}

// Save creates the Expertise in the database.
func (ec *ExpertiseCreate) Save(ctx context.Context) (*Expertise, error) {
	if _, ok := ec.mutation.ExpertiseName(); !ok {
		return nil, &ValidationError{Name: "ExpertiseName", err: errors.New("ent: missing required field \"ExpertiseName\"")}
	}
	var (
		err  error
		node *Expertise
	)
	if len(ec.hooks) == 0 {
		node, err = ec.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ExpertiseMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ec.mutation = mutation
			node, err = ec.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ec.hooks) - 1; i >= 0; i-- {
			mut = ec.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ec.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ec *ExpertiseCreate) SaveX(ctx context.Context) *Expertise {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ec *ExpertiseCreate) sqlSave(ctx context.Context) (*Expertise, error) {
	e, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	e.ID = int(id)
	return e, nil
}

func (ec *ExpertiseCreate) createSpec() (*Expertise, *sqlgraph.CreateSpec) {
	var (
		e     = &Expertise{config: ec.config}
		_spec = &sqlgraph.CreateSpec{
			Table: expertise.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: expertise.FieldID,
			},
		}
	)
	if value, ok := ec.mutation.ExpertiseName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: expertise.FieldExpertiseName,
		})
		e.ExpertiseName = value
	}
	if nodes := ec.mutation.ExpertiseUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   expertise.ExpertiseUserTable,
			Columns: []string{expertise.ExpertiseUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return e, _spec
}
