// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/beam19857/app/ent/expertise"
	"github.com/beam19857/app/ent/predicate"
	"github.com/beam19857/app/ent/user"
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// ExpertiseUpdate is the builder for updating Expertise entities.
type ExpertiseUpdate struct {
	config
	hooks      []Hook
	mutation   *ExpertiseMutation
	predicates []predicate.Expertise
}

// Where adds a new predicate for the builder.
func (eu *ExpertiseUpdate) Where(ps ...predicate.Expertise) *ExpertiseUpdate {
	eu.predicates = append(eu.predicates, ps...)
	return eu
}

// SetExpertiseID sets the ExpertiseID field.
func (eu *ExpertiseUpdate) SetExpertiseID(i int) *ExpertiseUpdate {
	eu.mutation.ResetExpertiseID()
	eu.mutation.SetExpertiseID(i)
	return eu
}

// AddExpertiseID adds i to ExpertiseID.
func (eu *ExpertiseUpdate) AddExpertiseID(i int) *ExpertiseUpdate {
	eu.mutation.AddExpertiseID(i)
	return eu
}

// SetExpertiseName sets the ExpertiseName field.
func (eu *ExpertiseUpdate) SetExpertiseName(s string) *ExpertiseUpdate {
	eu.mutation.SetExpertiseName(s)
	return eu
}

// SetLicenes sets the Licenes field.
func (eu *ExpertiseUpdate) SetLicenes(s string) *ExpertiseUpdate {
	eu.mutation.SetLicenes(s)
	return eu
}

// AddExpertiseUserIDs adds the ExpertiseUser edge to User by ids.
func (eu *ExpertiseUpdate) AddExpertiseUserIDs(ids ...int) *ExpertiseUpdate {
	eu.mutation.AddExpertiseUserIDs(ids...)
	return eu
}

// AddExpertiseUser adds the ExpertiseUser edges to User.
func (eu *ExpertiseUpdate) AddExpertiseUser(u ...*User) *ExpertiseUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return eu.AddExpertiseUserIDs(ids...)
}

// Mutation returns the ExpertiseMutation object of the builder.
func (eu *ExpertiseUpdate) Mutation() *ExpertiseMutation {
	return eu.mutation
}

// RemoveExpertiseUserIDs removes the ExpertiseUser edge to User by ids.
func (eu *ExpertiseUpdate) RemoveExpertiseUserIDs(ids ...int) *ExpertiseUpdate {
	eu.mutation.RemoveExpertiseUserIDs(ids...)
	return eu
}

// RemoveExpertiseUser removes ExpertiseUser edges to User.
func (eu *ExpertiseUpdate) RemoveExpertiseUser(u ...*User) *ExpertiseUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return eu.RemoveExpertiseUserIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (eu *ExpertiseUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(eu.hooks) == 0 {
		affected, err = eu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ExpertiseMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			eu.mutation = mutation
			affected, err = eu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(eu.hooks) - 1; i >= 0; i-- {
			mut = eu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (eu *ExpertiseUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *ExpertiseUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *ExpertiseUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (eu *ExpertiseUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   expertise.Table,
			Columns: expertise.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: expertise.FieldID,
			},
		},
	}
	if ps := eu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.ExpertiseID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: expertise.FieldExpertiseID,
		})
	}
	if value, ok := eu.mutation.AddedExpertiseID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: expertise.FieldExpertiseID,
		})
	}
	if value, ok := eu.mutation.ExpertiseName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: expertise.FieldExpertiseName,
		})
	}
	if value, ok := eu.mutation.Licenes(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: expertise.FieldLicenes,
		})
	}
	if nodes := eu.mutation.RemovedExpertiseUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   expertise.ExpertiseUserTable,
			Columns: []string{expertise.ExpertiseUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.ExpertiseUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   expertise.ExpertiseUserTable,
			Columns: []string{expertise.ExpertiseUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{expertise.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ExpertiseUpdateOne is the builder for updating a single Expertise entity.
type ExpertiseUpdateOne struct {
	config
	hooks    []Hook
	mutation *ExpertiseMutation
}

// SetExpertiseID sets the ExpertiseID field.
func (euo *ExpertiseUpdateOne) SetExpertiseID(i int) *ExpertiseUpdateOne {
	euo.mutation.ResetExpertiseID()
	euo.mutation.SetExpertiseID(i)
	return euo
}

// AddExpertiseID adds i to ExpertiseID.
func (euo *ExpertiseUpdateOne) AddExpertiseID(i int) *ExpertiseUpdateOne {
	euo.mutation.AddExpertiseID(i)
	return euo
}

// SetExpertiseName sets the ExpertiseName field.
func (euo *ExpertiseUpdateOne) SetExpertiseName(s string) *ExpertiseUpdateOne {
	euo.mutation.SetExpertiseName(s)
	return euo
}

// SetLicenes sets the Licenes field.
func (euo *ExpertiseUpdateOne) SetLicenes(s string) *ExpertiseUpdateOne {
	euo.mutation.SetLicenes(s)
	return euo
}

// AddExpertiseUserIDs adds the ExpertiseUser edge to User by ids.
func (euo *ExpertiseUpdateOne) AddExpertiseUserIDs(ids ...int) *ExpertiseUpdateOne {
	euo.mutation.AddExpertiseUserIDs(ids...)
	return euo
}

// AddExpertiseUser adds the ExpertiseUser edges to User.
func (euo *ExpertiseUpdateOne) AddExpertiseUser(u ...*User) *ExpertiseUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return euo.AddExpertiseUserIDs(ids...)
}

// Mutation returns the ExpertiseMutation object of the builder.
func (euo *ExpertiseUpdateOne) Mutation() *ExpertiseMutation {
	return euo.mutation
}

// RemoveExpertiseUserIDs removes the ExpertiseUser edge to User by ids.
func (euo *ExpertiseUpdateOne) RemoveExpertiseUserIDs(ids ...int) *ExpertiseUpdateOne {
	euo.mutation.RemoveExpertiseUserIDs(ids...)
	return euo
}

// RemoveExpertiseUser removes ExpertiseUser edges to User.
func (euo *ExpertiseUpdateOne) RemoveExpertiseUser(u ...*User) *ExpertiseUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return euo.RemoveExpertiseUserIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (euo *ExpertiseUpdateOne) Save(ctx context.Context) (*Expertise, error) {

	var (
		err  error
		node *Expertise
	)
	if len(euo.hooks) == 0 {
		node, err = euo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ExpertiseMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			euo.mutation = mutation
			node, err = euo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(euo.hooks) - 1; i >= 0; i-- {
			mut = euo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, euo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (euo *ExpertiseUpdateOne) SaveX(ctx context.Context) *Expertise {
	e, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return e
}

// Exec executes the query on the entity.
func (euo *ExpertiseUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *ExpertiseUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (euo *ExpertiseUpdateOne) sqlSave(ctx context.Context) (e *Expertise, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   expertise.Table,
			Columns: expertise.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: expertise.FieldID,
			},
		},
	}
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Expertise.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := euo.mutation.ExpertiseID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: expertise.FieldExpertiseID,
		})
	}
	if value, ok := euo.mutation.AddedExpertiseID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: expertise.FieldExpertiseID,
		})
	}
	if value, ok := euo.mutation.ExpertiseName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: expertise.FieldExpertiseName,
		})
	}
	if value, ok := euo.mutation.Licenes(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: expertise.FieldLicenes,
		})
	}
	if nodes := euo.mutation.RemovedExpertiseUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   expertise.ExpertiseUserTable,
			Columns: []string{expertise.ExpertiseUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.ExpertiseUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   expertise.ExpertiseUserTable,
			Columns: []string{expertise.ExpertiseUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	e = &Expertise{config: euo.config}
	_spec.Assign = e.assignValues
	_spec.ScanValues = e.scanValues()
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{expertise.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return e, nil
}
