// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/beam19857/app/ent/department"
	"github.com/beam19857/app/ent/expertise"
	"github.com/beam19857/app/ent/position"
	"github.com/beam19857/app/ent/predicate"
	"github.com/beam19857/app/ent/user"
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks      []Hook
	mutation   *UserMutation
	predicates []predicate.User
}

// Where adds a new predicate for the builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.predicates = append(uu.predicates, ps...)
	return uu
}

// SetDoctorID sets the DoctorID field.
func (uu *UserUpdate) SetDoctorID(i int) *UserUpdate {
	uu.mutation.ResetDoctorID()
	uu.mutation.SetDoctorID(i)
	return uu
}

// AddDoctorID adds i to DoctorID.
func (uu *UserUpdate) AddDoctorID(i int) *UserUpdate {
	uu.mutation.AddDoctorID(i)
	return uu
}

// SetDoctorName sets the DoctorName field.
func (uu *UserUpdate) SetDoctorName(s string) *UserUpdate {
	uu.mutation.SetDoctorName(s)
	return uu
}
// SetDoctorEmail sets the DoctorEmail field.
func (uu *UserUpdate) SetDoctorEmail(s string) *UserUpdate {
	uu.mutation.SetDoctorEmail(s)
	return uu
}

// SetDate sets the Date field.
func (uu *UserUpdate) SetDate(t time.Time) *UserUpdate {
	uu.mutation.SetDate(t)
	return uu
}

// SetUserDepartmentID sets the UserDepartment edge to Department by id.
func (uu *UserUpdate) SetUserDepartmentID(id int) *UserUpdate {
	uu.mutation.SetUserDepartmentID(id)
	return uu
}

// SetNillableUserDepartmentID sets the UserDepartment edge to Department by id if the given value is not nil.
func (uu *UserUpdate) SetNillableUserDepartmentID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetUserDepartmentID(*id)
	}
	return uu
}

// SetUserDepartment sets the UserDepartment edge to Department.
func (uu *UserUpdate) SetUserDepartment(d *Department) *UserUpdate {
	return uu.SetUserDepartmentID(d.ID)
}

// SetUserExpertiseID sets the UserExpertise edge to Expertise by id.
func (uu *UserUpdate) SetUserExpertiseID(id int) *UserUpdate {
	uu.mutation.SetUserExpertiseID(id)
	return uu
}

// SetNillableUserExpertiseID sets the UserExpertise edge to Expertise by id if the given value is not nil.
func (uu *UserUpdate) SetNillableUserExpertiseID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetUserExpertiseID(*id)
	}
	return uu
}

// SetUserExpertise sets the UserExpertise edge to Expertise.
func (uu *UserUpdate) SetUserExpertise(e *Expertise) *UserUpdate {
	return uu.SetUserExpertiseID(e.ID)
}

// SetUserPositionID sets the UserPosition edge to Position by id.
func (uu *UserUpdate) SetUserPositionID(id int) *UserUpdate {
	uu.mutation.SetUserPositionID(id)
	return uu
}

// SetNillableUserPositionID sets the UserPosition edge to Position by id if the given value is not nil.
func (uu *UserUpdate) SetNillableUserPositionID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetUserPositionID(*id)
	}
	return uu
}

// SetUserPosition sets the UserPosition edge to Position.
func (uu *UserUpdate) SetUserPosition(p *Position) *UserUpdate {
	return uu.SetUserPositionID(p.ID)
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// ClearUserDepartment clears the UserDepartment edge to Department.
func (uu *UserUpdate) ClearUserDepartment() *UserUpdate {
	uu.mutation.ClearUserDepartment()
	return uu
}

// ClearUserExpertise clears the UserExpertise edge to Expertise.
func (uu *UserUpdate) ClearUserExpertise() *UserUpdate {
	uu.mutation.ClearUserExpertise()
	return uu
}

// ClearUserPosition clears the UserPosition edge to Position.
func (uu *UserUpdate) ClearUserPosition() *UserUpdate {
	uu.mutation.ClearUserPosition()
	return uu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(uu.hooks) == 0 {
		affected, err = uu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uu.mutation = mutation
			affected, err = uu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uu.hooks) - 1; i >= 0; i-- {
			mut = uu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   user.Table,
			Columns: user.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: user.FieldID,
			},
		},
	}
	if ps := uu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.DoctorID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: user.FieldDoctorID,
		})
	}
	if value, ok := uu.mutation.AddedDoctorID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: user.FieldDoctorID,
		})
	}
	if value, ok := uu.mutation.DoctorName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldDoctorName,
		})
	}
	if value, ok := uu.mutation.Date(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: user.FieldDate,
		})
	}
	if uu.mutation.UserDepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.UserDepartmentTable,
			Columns: []string{user.UserDepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: department.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.UserDepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.UserDepartmentTable,
			Columns: []string{user.UserDepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: department.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.UserExpertiseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.UserExpertiseTable,
			Columns: []string{user.UserExpertiseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: expertise.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.UserExpertiseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.UserExpertiseTable,
			Columns: []string{user.UserExpertiseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: expertise.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.UserPositionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.UserPositionTable,
			Columns: []string{user.UserPositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: position.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.UserPositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.UserPositionTable,
			Columns: []string{user.UserPositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: position.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// SetDoctorID sets the DoctorID field.
func (uuo *UserUpdateOne) SetDoctorID(i int) *UserUpdateOne {
	uuo.mutation.ResetDoctorID()
	uuo.mutation.SetDoctorID(i)
	return uuo
}

// AddDoctorID adds i to DoctorID.
func (uuo *UserUpdateOne) AddDoctorID(i int) *UserUpdateOne {
	uuo.mutation.AddDoctorID(i)
	return uuo
}

// SetDoctorName sets the DoctorName field.
func (uuo *UserUpdateOne) SetDoctorName(s string) *UserUpdateOne {
	uuo.mutation.SetDoctorName(s)
	return uuo
}

// SetDate sets the Date field.
func (uuo *UserUpdateOne) SetDate(t time.Time) *UserUpdateOne {
	uuo.mutation.SetDate(t)
	return uuo
}

// SetUserDepartmentID sets the UserDepartment edge to Department by id.
func (uuo *UserUpdateOne) SetUserDepartmentID(id int) *UserUpdateOne {
	uuo.mutation.SetUserDepartmentID(id)
	return uuo
}

// SetNillableUserDepartmentID sets the UserDepartment edge to Department by id if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableUserDepartmentID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetUserDepartmentID(*id)
	}
	return uuo
}

// SetUserDepartment sets the UserDepartment edge to Department.
func (uuo *UserUpdateOne) SetUserDepartment(d *Department) *UserUpdateOne {
	return uuo.SetUserDepartmentID(d.ID)
}

// SetUserExpertiseID sets the UserExpertise edge to Expertise by id.
func (uuo *UserUpdateOne) SetUserExpertiseID(id int) *UserUpdateOne {
	uuo.mutation.SetUserExpertiseID(id)
	return uuo
}

// SetNillableUserExpertiseID sets the UserExpertise edge to Expertise by id if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableUserExpertiseID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetUserExpertiseID(*id)
	}
	return uuo
}

// SetUserExpertise sets the UserExpertise edge to Expertise.
func (uuo *UserUpdateOne) SetUserExpertise(e *Expertise) *UserUpdateOne {
	return uuo.SetUserExpertiseID(e.ID)
}

// SetUserPositionID sets the UserPosition edge to Position by id.
func (uuo *UserUpdateOne) SetUserPositionID(id int) *UserUpdateOne {
	uuo.mutation.SetUserPositionID(id)
	return uuo
}

// SetNillableUserPositionID sets the UserPosition edge to Position by id if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableUserPositionID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetUserPositionID(*id)
	}
	return uuo
}

// SetUserPosition sets the UserPosition edge to Position.
func (uuo *UserUpdateOne) SetUserPosition(p *Position) *UserUpdateOne {
	return uuo.SetUserPositionID(p.ID)
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// ClearUserDepartment clears the UserDepartment edge to Department.
func (uuo *UserUpdateOne) ClearUserDepartment() *UserUpdateOne {
	uuo.mutation.ClearUserDepartment()
	return uuo
}

// ClearUserExpertise clears the UserExpertise edge to Expertise.
func (uuo *UserUpdateOne) ClearUserExpertise() *UserUpdateOne {
	uuo.mutation.ClearUserExpertise()
	return uuo
}

// ClearUserPosition clears the UserPosition edge to Position.
func (uuo *UserUpdateOne) ClearUserPosition() *UserUpdateOne {
	uuo.mutation.ClearUserPosition()
	return uuo
}

// Save executes the query and returns the updated entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {

	var (
		err  error
		node *User
	)
	if len(uuo.hooks) == 0 {
		node, err = uuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uuo.mutation = mutation
			node, err = uuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uuo.hooks) - 1; i >= 0; i-- {
			mut = uuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	u, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return u
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (u *User, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   user.Table,
			Columns: user.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: user.FieldID,
			},
		},
	}
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing User.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := uuo.mutation.DoctorID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: user.FieldDoctorID,
		})
	}
	if value, ok := uuo.mutation.AddedDoctorID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: user.FieldDoctorID,
		})
	}
	if value, ok := uuo.mutation.DoctorName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldDoctorName,
		})
	}
	if value, ok := uuo.mutation.Date(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: user.FieldDate,
		})
	}
	if uuo.mutation.UserDepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.UserDepartmentTable,
			Columns: []string{user.UserDepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: department.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.UserDepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.UserDepartmentTable,
			Columns: []string{user.UserDepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: department.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.UserExpertiseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.UserExpertiseTable,
			Columns: []string{user.UserExpertiseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: expertise.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.UserExpertiseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.UserExpertiseTable,
			Columns: []string{user.UserExpertiseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: expertise.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.UserPositionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.UserPositionTable,
			Columns: []string{user.UserPositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: position.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.UserPositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.UserPositionTable,
			Columns: []string{user.UserPositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: position.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	u = &User{config: uuo.config}
	_spec.Assign = u.assignValues
	_spec.ScanValues = u.scanValues()
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return u, nil
}
