// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// DepartmentsColumns holds the columns for the "departments" table.
	DepartmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "department_id", Type: field.TypeInt},
		{Name: "department_name", Type: field.TypeString},
	}
	// DepartmentsTable holds the schema information for the "departments" table.
	DepartmentsTable = &schema.Table{
		Name:        "departments",
		Columns:     DepartmentsColumns,
		PrimaryKey:  []*schema.Column{DepartmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// ExpertisesColumns holds the columns for the "expertises" table.
	ExpertisesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "expertise_id", Type: field.TypeInt},
		{Name: "expertise_name", Type: field.TypeString},
		{Name: "licenes", Type: field.TypeString},
	}
	// ExpertisesTable holds the schema information for the "expertises" table.
	ExpertisesTable = &schema.Table{
		Name:        "expertises",
		Columns:     ExpertisesColumns,
		PrimaryKey:  []*schema.Column{ExpertisesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// PositionsColumns holds the columns for the "positions" table.
	PositionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "position_id", Type: field.TypeInt},
		{Name: "position_name", Type: field.TypeString},
	}
	// PositionsTable holds the schema information for the "positions" table.
	PositionsTable = &schema.Table{
		Name:        "positions",
		Columns:     PositionsColumns,
		PrimaryKey:  []*schema.Column{PositionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "doctor_id", Type: field.TypeInt},
		{Name: "doctor_name", Type: field.TypeString},
		{Name: "date", Type: field.TypeTime},
		{Name: "department_department_user", Type: field.TypeInt, Nullable: true},
		{Name: "expertise_expertise_user", Type: field.TypeInt, Nullable: true},
		{Name: "position_position_user", Type: field.TypeInt, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "users_departments_DepartmentUser",
				Columns: []*schema.Column{UsersColumns[4]},

				RefColumns: []*schema.Column{DepartmentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "users_expertises_ExpertiseUser",
				Columns: []*schema.Column{UsersColumns[5]},

				RefColumns: []*schema.Column{ExpertisesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "users_positions_PositionUser",
				Columns: []*schema.Column{UsersColumns[6]},

				RefColumns: []*schema.Column{PositionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DepartmentsTable,
		ExpertisesTable,
		PositionsTable,
		UsersTable,
	}
)

func init() {
	UsersTable.ForeignKeys[0].RefTable = DepartmentsTable
	UsersTable.ForeignKeys[1].RefTable = ExpertisesTable
	UsersTable.ForeignKeys[2].RefTable = PositionsTable
}
