/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntExpertiseEdges
 */
export interface EntExpertiseEdges {
    /**
     * ExpertiseUser holds the value of the ExpertiseUser edge.
     * @type {Array<EntUser>}
     * @memberof EntExpertiseEdges
     */
    expertiseUser?: Array<EntUser>;
}

export function EntExpertiseEdgesFromJSON(json: any): EntExpertiseEdges {
    return EntExpertiseEdgesFromJSONTyped(json, false);
}

export function EntExpertiseEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntExpertiseEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expertiseUser': !exists(json, 'expertiseUser') ? undefined : ((json['expertiseUser'] as Array<any>).map(EntUserFromJSON)),
    };
}

export function EntExpertiseEdgesToJSON(value?: EntExpertiseEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expertiseUser': value.expertiseUser === undefined ? undefined : ((value.expertiseUser as Array<any>).map(EntUserToJSON)),
    };
}


